Before you turn this assignment in, make sure everything runs as expected by going to the menubar and running: 

**Kernel $\rightarrow$ Restart & Run All**

Please replace all spots marked with `# ADD YOUR CODE HERE` or `ADD YOUR ANSWER HERE`.

And start by filling in your name and student_id below:

In [ ]:
NAME = ""
STUDENT_ID = ""

In [ ]:
assert len(NAME) > 0, "Please fill in your name"
assert len(STUDENT_ID) > 0, "Please fill in your student id"

---

In [ ]:
import doctest

import altair as alt
import numpy as np
import pandas as pd

from typing import Callable, List

In [ ]:
if __name__ == "__main__":
    # Enable doctests in Jupyter:
    def test(fn: Callable):
        doctest.run_docstring_examples(fn, globals(), verbose=True, name=fn.__name__)
else:
    # Disable doctests in autograding setup
    def test(fn: Callable): pass

# Week 2 - Evaluation

Welcome back to the second assignment of the search engines course. We will use this assignment to deepen our understanding of the evaluation metrics introduced in this week's lecture. In part I, we look into relevance in information retrieval. In part II, we learn about set-based retrieval metrics. And finally, part III looks at metrics that take the order of our search results into account.

For any questions, problems, or feedback, please contact your TA. Good luck with the assignment!


### Resources

📚 [Croft, Metzler, and Strohman - Chapter 8](https://ciir.cs.umass.edu/downloads/SEIRiP.pdf#page=321)

📚 [Manning, Raghavan, Schütze - Chapter 8](https://nlp.stanford.edu/IR-book/pdf/08eval.pdf)

🌐 [Numpy - Basics](https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array)

# Part I - Relevance

### 1.1 The notion of relevance

Last week, we learned about the user's information need and the concept of relevance. So let's begin this assignment on evaluating search engines by refreshing what relevance means.


📝 Which of these following statements are correct?

a.) A document must contain all query words to be relevant.

b.) Relevance can be binary (not relevant / relevant) or graded (e.g., not relevant / somewhat relevant / very relevant).

c.) Relevance is assessed over all documents in a corpus.

d.) Relevance tries to capture how well a document fits a given query, not a user’s information need.

e.) A common assumption is that the relevance of one document is independent of other documents.

f.) Typically, trained search engine evaluators are asked to assess the relevance of search results.

g.) Relevance labels are not always valid over time.

In [ ]:
# ADD YOUR ANSWER HERE
answer_1_1_a = False
answer_1_1_b = False
answer_1_1_c = False
answer_1_1_d = False
answer_1_1_e = False
answer_1_1_f = False
answer_1_1_g = False

### 1.2 Critique of relevance

Document relevance was (and is) arguably a very important concept in information retrieval. However, the concept is not without criticism (📚 [Manning et al.](https://nlp.stanford.edu/IR-book/pdf/08eval.pdf)).

📝 List at least three potential issues of the relevance concept and explain each with an example:

<div class="alert alert-info">ADD YOUR ANSWER HERE</div>

### 1.3 User satisfaction
Search engines have to consider many more aspects beyond document relevance to satisfy users. 

📝 Think of at least three factors beyond document relevance that are expected to impact user satisfaction in web search.

<div class="alert alert-info">ADD YOUR ANSWER HERE</div>

# Part II - Unranked / Set-based Evaluation Metrics

## 2.1 Precision and recall

The most basic evaluation metrics for search engines are set-based. These metrics treat search results as an unordered set of documents and measure how many relevant or non-relevant items were retrieved, but not in which order. The two most common metrics are [precision](https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Precision) and [recall](https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Recall).

Precision is the fraction of documents in our search results that are relevant. Looking at the top 20 search result of our Google page, for example, precision tells you how many items of these 20 are actually relevant:

$
\textrm{precision} = \normalsize\frac{\textrm{\# retrieved relevant items}}{\textrm{\# retrieved items}}
$

Recall is the fraction of relevant documents that were retrieved. Meaning, if there are 50 relevant documents overall for our given information need, recall tells you how many of these 50 were retrieved in our search results.

$
\textrm{recall} = \normalsize\frac{\textrm{\# retrieved relevant items}}{\textrm{\# all relevant items}}
$

### Ranges of precision and recall
📝 Given a collection of 100 documents, of which 60 are relevant. What is the minimum and maximum possible precision and recall if you return 50 documents?

In [ ]:
# ADD YOUR ANSWER HERE
min_precision = 0.0
max_precision = 0.0

min_recall = 0.0
max_recall = 0.0

In [ ]:
assert 0 <= min_precision and min_precision <= 1, "Precision be between 0.0 and 1.0"
assert 0 <= max_precision and max_precision <= 1, "Precision be between 0.0 and 1.0"
assert 0 <= min_recall and min_recall <= 1, "Precision be between 0.0 and 1.0"
assert 0 <= max_recall and max_recall <= 1, "Precision be between 0.0 and 1.0"

## 2.2 Precision@k

Now, let's actually implement precision and recall. Complete the two functions below. Assume the `scores` parameter is an array of binary document relevance for a given ranking.

📝 Begin by implementing [Precision@k](https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Precision_at_k), which only considers the top k documents for calculating precision.

<div class="alert alert-warning">
💡 Note: To make mathematical operations on the scores array easier, the supplied parameter is a numpy array NOT a Python list. You can find an introduction to numpy in the resource section at the top of the notebook.
</div>

In [ ]:
def precision(scores: np.ndarray, k: int) -> float:
    """
    >>> precision(np.array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1]), 4)
    0.25
    >>> precision(np.array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1]), 1)
    1.0
    >>> precision(np.array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1]), 10)
    0.5
    >>> precision(np.array([1, 1, 1, 0, 0]), 3)
    1.0
    >>> precision(np.array([0, 0, 0, 0, 0]), 3)
    0.0
    >>> precision(np.array([1, 0, 0, 0, 0]), 5)
    0.2
    >>> precision(np.array([1, 0, 0, 0, 0]), 4)
    0.25
    >>> precision(np.array([1, 0, 0, 0, 0]), 100)
    0.2
    """
    precision = 0.0

    # ADD YOUR CODE HERE
    
    return precision

In [ ]:
test(precision)

## 2.3 Recall@k

📝 Next implement recall and similarly consider only the top k documents as your search result. Use the number of all relevant documents in the scores array (even if they are not in the top k) as the total number of relevant documents in the corpus. If there are no relevant documents in the corpus to be retrieved, your recall should be 0.

In [ ]:
def recall(scores: np.ndarray, k: int) -> float:
    """
    >>> recall(np.array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1]), 5)
    0.4
    >>> recall(np.array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1]), 1)
    0.2
    >>> recall(np.array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1]), 10)
    1.0
    >>> recall(np.array([1, 1, 1, 0, 0]), 3)
    1.0
    >>> recall(np.array([1, 1, 1, 0, 1]), 3)
    0.75
    >>> recall(np.array([0, 0, 0, 0, 1]), 5)
    1.0
    >>> recall(np.array([0, 0, 0, 0, 0]), 3)
    0.0
    >>> recall(np.array([0, 0, 0, 0, 1]), 100)
    1.0
    """
    recall = 0.0

    # ADD YOUR CODE HERE
    
    return recall

In [ ]:
test(recall)

## 2.4 Precision-Recall Graph

In [ ]:
def plot(precision, recall, name="Precision-Recall", stepped=False):
    assert len(recall) == len(precision), "Recall and precision arrays must have the same length"
    df = pd.DataFrame({"precision": precision, "recall": recall, "name": name})

    return alt.Chart(df, width=300, height=300).mark_line(
        point=True,
        interpolate="step-before" if stepped else "linear"
    ).encode(
        x=alt.X("recall:Q", title="Recall").scale(domain=(0, 1)),
        y=alt.Y("precision:Q", title="Precision").scale(domain=(0, 1)),
        color=alt.Color("name", title=""),
        tooltip=["precision", "recall"]
    )

### Reading the Precision-Recall Graph

Computing precision and recall at different top k ranks is a common way to gain insight into the performance of different ranking algorithms. However, we also loose quite a bit of detail in the process, especially when comparing precision/recall across different queries or entire systems. Precision-recall graphs are one method we've covered in the lecture that can be helpful to get a more detailed view of ranking performance across different recall levels.

We show a graph below for the following ranking of relevant/non-relevant items: 
```
[1, 0, 1, 1, 0, 1, 0, 0, 0, 1]
```
You read these plots from left to right. We start with a relevant document leading to a precision of 1, followed by a non-relevant document which drops precision to 0.5 but does not change recall. The third document is relevant again leading to a bump in precision and recall, and so on.

In [ ]:
precision_at_k = np.array([1/1, 1/2, 2/3, 3/4, 3/5, 4/6, 4/7, 4/8, 4/9, 5/10])
recall_at_k = np.array([1/5, 1/5, 2/5, 3/5, 3/5, 4/5, 4/5, 4/5, 4/5, 5/5])

plot(
    precision=precision_at_k,
    recall=recall_at_k,
)

### Interpolating the Precision-Recall Graph

The graph above shows precision and recall for a single query. To average performance across queries, it’s common to calculate precision at standard recall levels (e.g., 0.0, 0.1, 0.2, etc.). However, since queries have different numbers of relevant documents, their recall levels vary (e.g., a query with three documents can have recall levels 0, 1/3, 2/3, 1.0, while a query with five documents has 0, 0.2, 0.4, 0.6, 0.8, 1.0). To address this, we need a method to calculate precision at fixed recall levels, with the following interpolation method being the most common approach in information retrieval.

#### Interpolated precision  (📚 [Croft et al.](https://ciir.cs.umass.edu/downloads/SEIRiP.pdf#page=340)):
Given a set $ S $ of observed pairs of precision@k and recall@k values $(P, R)$, the **interpolated precision** at any recall level $R$ is defined as:

$
\text{interpolated\_precision@recall}(R) = \max \left\{P': R' \geq R \text{ and } (R', P') \in S\right\}
$

This means that the interpolated precision at a given recall level $R$ is the highest precision observed at any recall level $R'$ that is greater than or equal to $R$.


#### Example
Consider the following precision and recall values for different k:

```python
precision = [0.0, 0.5, 2/3]
recall = [0.0, 0.5, 1.0]
```

To compute the interpolated precision at recall level `0.25`, we first identify relevant recall levels: Look at recall levels greater than or equal to `0.25`. In this case, the relevant recall levels are `0.5` and `1.0`. Second, we find the maximum precision: Among these relevant recall levels, find the maximum precision value. Here, the precision values are `0.5` and `2/3`. Thus, the interpolated precision at recall level `0.25` is `2/3`.


#### Implement interpolation for the PR Graph
📝 Complete the method below that takes a list of recall levels and returns the interpolated precision values for each recall level by finding the maximum precision at or above each specified recall level. You can visualize your interpolation method with the code below the tests.

In [ ]:
def interpolate(precision, recall, recall_levels):
    """
    >>> interpolate(precision=np.array([0/1, 1/2, 2/3]), recall=np.array([0/2, 1/2, 2/2]), recall_levels=np.array([0.25])).round(3)
    array([0.667])
    >>> interpolate(precision=np.array([1, 0.5, 1/3, 0.5, 0.6]), recall=np.array([1/3, 1/3, 1/3, 2/3, 1]), recall_levels=np.array([0, 0.25, 0.5, 0.75, 1.0]))
    array([1. , 1. , 0.6, 0.6, 0.6])
    >>> interpolate(precision=np.array([0, 0, 1/3, 0.5]), recall=np.array([0/2, 0/2, 1/2, 2/2]), recall_levels=np.array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]))
    array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
    >>> interpolate(precision=np.array([1, 1/2, 1/3, 1/4]), recall=np.array([1/1, 1/1, 1/1, 1/1]), recall_levels=np.array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]))
    array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
    >>> interpolate(precision=np.array([1, 1/2, 1/3, 2/4]), recall=np.array([1/2, 1/2, 1/2, 2/2]), recall_levels=np.array([0, 0.25, 0.5, 0.75, 1.0]))
    array([1. , 1. , 1. , 0.5, 0.5])
    """
    interpolated_precision = []

    # ADD YOUR CODE HERE
    
    return np.array(interpolated_precision)

In [ ]:
test(interpolate)

In [ ]:
recall_levels = np.array([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
interpolated_precision = interpolate(precision_at_k, recall_at_k, recall_levels)

(
    plot(precision=precision_at_k, recall=recall_at_k, name="Precision-Recall") +
    plot(precision=interpolated_precision, recall=recall_levels, name="Precision-Recall (Interpolated)", stepped=True)
)

## 2.5 F1 - Summarizing Precision and Recall

To conclude the section on set-based retrieval, we look at a common way to summarize precision and recall into a single score: the [F1 score](https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#F-score_/_F-measure). The F1 score is the harmonic mean of precision and recall.

$\textrm{harmonic}(R, P) = \frac{2\cdot P \cdot R}{P + R}$

$\textrm{arithmetic}(R, P) = \frac{P + R}{2}$

📝 What is the benefit of using the harmonic mean of precision and recall over the arithmetic mean?

<div class="alert alert-info">ADD YOUR ANSWER HERE</div>

# Part III - Ranked Retrieval

All metrics so far have ignored the order of search results. Precision does not change if the relevant documents are at the very top or at the very bottom of our search results (as long as they were retrieved). We know, however, that order is important since users tend to look at documents at higher positions more often and usually don't scroll down to the bottom (a phenomena called position bias).

After this course, you should be familiar with **three common rank-sensitive metrics: Average Precision (AP), MRR, and nDCG.** In the following, we will implement MRR and nDCG.

## 3.1 Reciprocal Rank

A simple, but common, metric in web search is to measure the **rank of the first relevant item** in your search results. Taking the inverse (or reciprocal) of this rank gives you the reciprocal rank measure for a given ranking:

$\text{reciprocal\_rank} = \frac{1}{\text{rank of first relevant item}}$

As above, ranks are counted starting at one. If the first search result is relevant your reciprocal rank is 1/1, if the third result is the first relevant document, the reciprocal rank is 1/3. Averaging this metric over multiple rankings gives you the [mean reciprocal rank (MRR)](https://en.wikipedia.org/wiki/Mean_reciprocal_rank) for a given search engine.

📝 Complete the reciprocal rank function below. Consider only the top k elements of the scores array. Return zero if no document in the ranking is relevant.

<div class="alert alert-warning">
💡 Tip: The numpy function "np.nonzero(array)" returns the indices of all array entries that are not zero and could be helpful.
</div>

In [ ]:
def reciprocal_rank(scores: np.ndarray, k: int) -> float:
    """
    >>> reciprocal_rank(np.array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1]), 5)
    1.0
    >>> reciprocal_rank(np.array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1]), 10)
    0.25
    >>> reciprocal_rank(np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), 10)
    0.1
    >>> reciprocal_rank(np.array([0, 0, 0, 0, 1]), 5)
    0.2
    >>> reciprocal_rank(np.array([0, 0, 0, 0, 1]), 4)
    0.0
    >>> reciprocal_rank(np.array([0, 0, 0, 0, 1]), 100)
    0.2
    """
    reciprocal_rank = 0.0

    # ADD YOUR CODE HERE
    
    return reciprocal_rank

In [ ]:
test(reciprocal_rank)

## 3.2 Graded relevance and DCG

The last metric we will consider in this assignment is the normalized discounted cumulative gain or [nDCG](https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Normalized_DCG) metric. This metric makes two assumptions:

* First, highly relevant items are more useful than somewhat relevant items. This assumption moves beyond the notion of binary relevance to a graded relevance scale (often on a 5 point scale, from 0 to 4). Graded relevance here signifies the **gain** a user has from looking at a given document.

* Second, ranking relevant items lower makes them less useful since the user is less likely to look at them (position bias). Meaning, the relevance of an item is reduced or **discounted** based on its position. 

Putting those two assumptions together results in the discounted cumulative gain metric (DCG). Let $i$ be the rank of a document in a ranking. Then, the DCG is the relevance of the document discounted by the log of the rank (adding 1 to avoid division by zero) at which it is displayed:

$\textrm{DCG} = \normalsize \sum_{i=1}^{N} \frac{relevance_i}{\log_2(i + 1)}$

📝 Compute the DCG for a given ranking. Note that the score array has now graded relevance labels from 0 to 4. As before take the parameter k into account.

In [ ]:
def dcg(scores: np.ndarray, k: int) -> float:
    """
    >>> dcg(np.array([4, 0, 2, 0, 0, 0, 3, 0]), 8)
    6.0
    >>> dcg(np.array([0, 0, 4, 0, 0, 0, 3, 0]), 8)
    3.0
    >>> dcg(np.array([0, 0, 1, 0, 0, 0, 3, 0]), 8)
    1.5
    >>> dcg(np.array([0, 0, 1, 0, 0, 0, 3, 0]), 4)
    0.5
    >>> dcg(np.array([0, 0, 0, 0, 0, 0, 3, 0]), 4)
    0.0
    >>> dcg(np.array([0, 0, 1, 0, 0, 0, 3, 0]), 100)
    1.5
    >>> round(dcg(np.array([4, 3, 2, 1, 0, 0, 0, 0]), 8), 6)
    7.323466
    >>> round(dcg(np.array([4, 3, 2, 1, 0, 0, 0, 0]), 4), 6)
    7.323466
    >>> round(dcg(np.array([0, 1, 2, 3, 4]), 5), 6)
    4.470371
    >>> round(dcg(np.array([0, 1, 2, 3, 4]), 4), 6)
    2.922959
    >>> round(dcg(np.array([0, 1, 2, 3, 4]), 3), 6)
    1.63093
    """
    dcg = 0.0

    # ADD YOUR CODE HERE
    
    return dcg

In [ ]:
test(dcg)

## 3.3 nDCG

Since the value of DCG depends on the relevance of the documents in the ranking (and thus varies highly between different rankings / queries), it is usually normalized by the maximum DCG possible for a given ranking. I.e., we normalize by the score for the ideal ranking of the documents in a given ranking:

$\textrm{nDCG} = \normalsize \frac{\textrm{DCG}}{\textrm{Ideal DCG}}$

Consider this example ranking of five documents with a relevance between 0 and 4.
```
[2, 3, 1, 4, 0],  DCG ≈ 6.12
```

While the ideal ranking would result in a DCG of:
```
[4, 3, 2, 1, 0], DCG ≈ 7.32
```

Dividing the DCG of our ranking by its ideal version results in an nDCG of 0.84. Note that through this normalization nDCG is always between 0 and 1.


📝 Reuse the above dcg function to compute the nDCG score for a ranking. Take the cutoff parameter k into account. If there is no relevant document in your ranking, and the ideal DCG is 0, return 0 as the nDCG value.

In [ ]:
def ndcg(scores: np.ndarray, k: int) -> float:
    """
    >>> ndcg(np.array([4, 3, 2, 1, 1, 1, 0, 0]), 8)
    1.0
    >>> round(ndcg(np.array([0, 0, 1, 1, 1, 2, 3, 4]), 8), 6)
    0.532051
    >>> round(ndcg(np.array([4, 0, 1, 1, 1, 2, 3, 0]), 8), 6)
    0.871496
    >>> ndcg(np.array([0, 0, 0, 0, 4, 3, 2, 1]), 4)
    0.0
    >>> round(ndcg(np.array([4, 0, 1, 1, 1, 2, 3, 0]), 100), 6)
    0.871496
    >>> ndcg(np.array([0, 0, 0, 0]), 3)
    0.0
    """
    ndcg = 0.0

    # ADD YOUR CODE HERE
    
    return ndcg

In [ ]:
test(ndcg)

## 3.4 Contrasting nDCG and MRR

MRR and nDCG measure different aspects of a search engine, and they do not not always have to agree with each other.

📝 Construct two rankings A and B below so that:

- **A** has a higher MRR but a lower nDCG than B
- **B** has a lower MRR but a higher nDCG than A 

Use only exactly five documents with relevance: [0, 1, 2, 3, 4]

Since reciprocal rank considers only binary relevance, consider the single document with relevance 4 as the only relevant document in a binary setting. We added some boilerplate code to convert your answer to binary relevance to use your reciprocal_rank function below.

In [ ]:
ranking_a = np.array([
    # ADD YOUR CODE HERE
])
ranking_b = np.array([
    # ADD YOUR CODE HERE
])

# Convert to binary relevance:
binary_ranking_a = np.where(ranking_a == 4, 1, 0)
binary_ranking_b = np.where(ranking_b == 4, 1, 0)

print(f"Ranking A, nDCG: {ndcg(ranking_a, 5)}, MRR: {reciprocal_rank(binary_ranking_a, 5)}")
print(f"Ranking B, nDCG: {ndcg(ranking_b, 5)}, MRR: {reciprocal_rank(binary_ranking_b, 5)}")

## 3.5 When to optimize for nDCG or MRR?

📝 Lastly, in which real-world search settings would ranking A (high MRR) or B (high nDCG) be preferrable?

<div class="alert alert-info">ADD YOUR ANSWER HERE</div>